<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf2b9f9b4fe4c27a721f070333b4f4940
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf2b9f9b4fe4c27a721f070333b4f4940::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf2b9f9b4fe4c27a721f070333b4f4940::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
